### PR TITLE
docker-compose - backend selection on startup

### PR DESCRIPTION
**Pull request by desmax74**
See: https://github.com/guacsec/guac/issues/1435
and  https://github.com/guacsec/guac/issues/1434

The PR [1434](https://github.com/guacsec/guac/issues/1434)  enable the startup of guac with docker compose choosing the backend

    In memory docker compose -f docker-compose.yml -f container_files/mem.yaml up

    Arango docker compose -f docker-compose.yml -f container_files/arango.yaml up

    Ent docker compose -f docker-compose.yml -f container_files/ent.yaml up

    Neo4j docker compose -f docker-compose.yml -f container_files/neo4j.yaml up

In the make file the `make start-service` run the in memory option

### CODE REVIEW

**Comment by desmax74** [comment]
@lumjjb worth to mention the other backends options here (ent/neo4j/arango) ?

**Comment by desmax74** [comment]
@mihaimaruseac

**Review by pxp928 — APPROVED** [review]

**Comment by pxp928** [comment]
> @lumjjb worth to mention the other backends options here (ent/neo4j/arango) ?

Not yet. Once those are fully supported, we can call them out.

**Comment by pxp928** [comment]
@desmax74 please reopen this PR once the revert PR has gone through and we can get the changes in for next release.

**Pull request merged**
