### PR TITLE
Signed-off-by: Jatin Vishwakarma <119022686+coddingjatin@users.noreply.github.com>

### PR DESCRIPTION
**Pull request by coddingjatin**
Was facing problem related  squashing all the commits into a single one so done changes in the forked one

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
You need to do

```
git add <the files>
git commit -S
git push -u
```

The Signed-off-by line should not be the first in the commit.

You only need to have one single commit.

**Comment by mihaimaruseac** [comment]
Also, it's weird that now you have 2 files with different letter casing. Only one should be needed.

**Comment by funnelfiasco** [comment]
@coddingjatin thanks for your contribution! I see that you have two similar pull requests open. Which would you rather work in? I'll close the other.

**Comment by funnelfiasco** [comment]
Actually, now that I look at the content of the change, it's clearly irrelevant and possibly AI-generated. Closing this PR as invalid.

**Comment by mihaimaruseac** [comment]
I should have checked the contents too, not just the style

**Comment by coddingjatin** [comment]
Soo Sorry for misunderstanding and problems you guys faced , Actually i had taken help of AI to make content more effective and well mannered. But surely will contribute in future , Thank you for  giving your time. And Closing this PR

**Pull request closed without merging**
