### PR TITLE
Update guac-visualizer.md

### PR DESCRIPTION
**Pull request by pgbhagat**
Correcting the git clone command

### CODE REVIEW

**Review by jeffmendoza — APPROVED** [review]

**Review by pxp928 — APPROVED** [review]
Just need to sign the commit and good to go! Thanks @pgbhagat

**Comment by pgbhagat** [comment]
> 

Let me check what needs to be done for this. I see the commit has 'verified' badge though.

**Comment by pxp928** [comment]
@pgbhagat you need to do a `-s` when doing the commit. For example:  `git commit -m "initial commit" -s`. That will fix the issue.

**Comment by pgbhagat** [comment]
Signed the commit, done

**Comment by pxp928** [comment]
@pgbhagat you will have to sign both commits (all commits).

**Comment by funnelfiasco** [comment]
This change was obviated by 458a3ec. Closing the PR. Thanks for your work @pgbhagat

**Pull request closed without merging**
