### PR TITLE
Bring output of 'docker compose ls --filter "name=guac"' up-to-date

### PR DESCRIPTION
**Pull request by nchelluri**
In https://github.com/guacsec/guac/issues/2002 Mike noted that the output in the docs is out-of-date, so I brought it up-to-date here. I hacked up my own output to leave Brandon L's name there because it felt weird putting my own in there when I am not a maintainer of guac.

For posterity, here is what I saw:

```bash
nchelluri@Narsimhams-MBP guac-demo % docker compose ls --filter "name=guac"
NAME                STATUS              CONFIG FILES
guac                running(2)          /Users/nchelluri/dev/guac/docker-compose.yml,/Users/nchelluri/dev/guac/container_files/mem.yaml
guac-demo           running(5)          /Users/nchelluri/dev/guac-demo/guac-demo-compose.yaml
nchelluri@Narsimhams-MBP guac-demo % docker compose ls
NAME                STATUS              CONFIG FILES
container_files     running(1)          /Users/nchelluri/dev/guac/container_files/guac-demo-compose.yaml
guac                running(2)          /Users/nchelluri/dev/guac/docker-compose.yml,/Users/nchelluri/dev/guac/container_files/mem.yaml
guac-demo           running(5)          /Users/nchelluri/dev/guac-demo/guac-demo-compose.yaml
nchelluri@Narsimhams-MBP guac-demo %
```

### CODE REVIEW

**Comment by nchelluri** [comment]
I'm not 100% sure the output looks reasonable. It is not from a release (the compose file would be https://github.com/guacsec/guac/releases/download/v0.7.2/guac-demo-compose.yaml if it was) and I manually downloaded the guac `main` `container_files/guac-demo-compose.yaml` and put it in `~/dev/guac-demo`. So please edit as needed.

**Comment by pxp928** [comment]
@nchelluri looks to be a formatting issue.

**Comment by nchelluri** [comment]
> @nchelluri looks to be a formatting issue.

Oops, I think you meant that the header line was there twice. If so, fixed in aa743ee7d16ca26b2236faf60d2284650427cd2f.

**Review by mlieberman85 — APPROVED** [review]
lgtm

**Comment by funnelfiasco** [comment]
@nchelluri there are a lot of files that look like they only have formatting changes (particularly the location of line breaks). Can you separate those out? (Most of them can probably just be dropped. I don't particularly like the current style in the docs, but changing the word where the line breaks doesn't fix my dislike 😄 )

**Comment by nchelluri** [comment]
> @nchelluri there are a lot of files that look like they only have formatting changes (particularly the location of line breaks). Can you separate those out? (Most of them can probably just be dropped. I don't particularly like the current style in the docs, but changing the word where the line breaks doesn't fix my dislike 😄 )

The reason I did this is: https://github.com/guacsec/guac-docs/pull/129#issuecomment-2214285590

The "format" check was failing, Parth noted it and so I fixed it (probably can't merge the PR without doing an override with that check failing). As you can see from my previous comment, the check was failing when I ran it locally on the `main` branch, too. I really don't know much more about this repo. The only change I actually _wanted_ to make was 8eca42e30ea38a59427c3bfe284818debcfe82d5 and the follow-up 5c50998b1a5e74ff3f20679cadd8356fff0fe9f5 which was just a fat-finger fix.

I am not sure what to do at this point. Happy to go any direction.

**Comment by funnelfiasco** [comment]
Sadness. I say :shipit: then. Updated docs are more important than the Platonic Ideal of git history :-)

**Pull request merged**
