### PR TITLE
Fix typo in GUAC REST Server description

### PR DESCRIPTION
**Pull request by ANIRUDH-333**

### CODE REVIEW

**Comment by funnelfiasco** [comment]
Thanks for the contribution, @ANIRUDH-333! These changes look good to me. You will need to include a Developer Certificate of Origin signoff in order for us to merge these changes. I suggest squashing your two commits into one when you add the signoff, but that's not required. If you need help with that, you can message me in the #guac channel on OpenSSF Slack. See the [https://guac.sh/community](community page) for details if you need it.

**Comment by ANIRUDH-333** [comment]
> Thanks for the contribution, @ANIRUDH-333! These changes look good to me. You will need to include a Developer Certificate of Origin signoff in order for us to merge these changes. I suggest squashing your two commits into one when you add the signoff, but that's not required. If you need help with that, you can message me in the #guac channel on OpenSSF Slack. See the [community page](https://guac.sh/community) for details if you need it.

Thank you @funnelfiasco for the suggestion. I have squashed the commits and added DCO also. Can you please review it now?

**Review by funnelfiasco — APPROVED** [review]
LGTM

**Review by pxp928 — APPROVED** [review]
Thank You!

**Pull request merged**
